name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x (for workspaces)
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build:packages --if-present
      - name: Run tests
        run: npm test -- --ci
